set -g mouse on
set -s set-clipboard on
set -s focus-events on

set -g mode-keys vi

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Automatically renumber windows to fill gaps
set -g renumber-windows on
