theme = "naysayer_fixed"
# theme = "noctalia"

[editor]
clipboard-provider = "wayland"
line-number = "relative"
mouse = false
end-of-line-diagnostics = "disable"

[editor.auto-save]
focus-lost = true
afterdelay.enables = true
afterdelay.timeout = 5000 # 5 seconds of not editing the file will trigger this

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

[keys.insert]
"C-h" = "signature_help"
