[language-server.typescript-language-server]
args = [ "--stdio" ]
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }

[[language]]
name = "odin"
auto-format = true

[[language]]
name = "go"
auto-format = true
