[language-server.typescript-language-server]
command = "tsgo"
args = [ "--lsp", "--stdio" ]
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }

[[language]]
name = "odin"
auto-format = true

[[language]]
name = "go"
formatter = { command = "gofmt" }
auto-format = true
